#ifndef VULKAN_POINTERS_HPP
#define VULKAN_POINTERS_HPP

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

extern PFN_vkCreateAccelerationStructureKHR fpCreateAccelerationStructureKHR;
extern PFN_vkDestroyAccelerationStructureKHR fpDestroyAccelerationStructureKHR;
extern PFN_vkGetAccelerationStructureBuildSizesKHR fpGetAccelerationStructureBuildSizesKHR;
extern PFN_vkCmdBuildAccelerationStructuresKHR fpCmdBuildAccelerationStructuresKHR;
extern PFN_vkGetAccelerationStructureDeviceAddressKHR fpGetAccelerationStructureDeviceAddressKHR;

extern PFN_vkCreateRayTracingPipelinesKHR fpCreateRayTracingPipelinesKHR;
extern PFN_vkGetRayTracingShaderGroupHandlesKHR fpGetRayTracingShaderGroupHandlesKHR;
extern PFN_vkCmdTraceRaysKHR fpCmdTraceRaysKHR;
extern PFN_vkCmdTraceRaysIndirectKHR fpCmdTraceRaysIndirectKHR;

extern PFN_vkBuildAccelerationStructuresKHR fpBuildAccelerationStructuresKHR;
extern PFN_vkGetBufferDeviceAddressKHR fpGetBufferDeviceAddressKHR;

extern PFN_vkCmdBeginDebugUtilsLabelEXT fpCmdBeginDebugUtilsLabelEXT;
extern PFN_vkCmdEndDebugUtilsLabelEXT fpCmdEndDebugUtilsLabelEXT;

#endif // !VULKAN_POINTERS_HPP
